{% set name = "xxHash" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Cyan4973/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: baee0c6afd4f03165de7a4e67988d16f0f2b257b51d0e3cb91909302a26a79c4

build:
  number: 0
  run_exports:
    # The recent history has been quite unstable: https://abi-laboratory.pro/?view=timeline&l=xxhash
    - {{ pin_subpackage("xxhash", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - cmake  # [win]

test:
  commands:
    - xxhsum --help

about:
  home: http://www.xxhash.com/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Extremely fast hash algorithm
  description: |
    xxHash is an Extremely fast Hash algorithm, running at RAM speed limits. It
    successfully completes the SMHasher test suite which evaluates collision,
    dispersion and randomness qualities of hash functions. Code is highly
    portable, and hashes are identical on all platforms (little / big endian).
  dev_url: https://github.com/Cyan4973/xxHash
  doc_url: https://github.com/Cyan4973/xxHash

extra:
  recipe-maintainers:
    - beckermr
    - xhochy
